# Site settings
title: Nathan Lippi
email: nathan.lippi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Find a bit more about me, here!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nathanlippi
github_username:  nathanlippi

# Build settings
markdown: kramdown
